use crate::{Assignment, Monster, Quest, WORLD_STATE, WorldState};

impl Monster {
    pub fn can_limpwurt_kill(self) -> bool {
        use Monster::*;
        match self {
            AberrantSpectres => false,
            AbyssalDemons => false,
            Ankous => true,
            Aviansie => false,
            Banshees => false,
            Basilisks => false,
            Bats => true,
            Bears => true,
            Birds => true,
            BlackDemons => true,
            Bloodveld => WORLD_STATE != WorldState::Limp2024,
            BlueDragons => false,
            BrineRats => false,
            CaveBugs => true,
            CaveCrawlers => true,
            CaveHorrors => false,
            CaveKraken => false,
            CaveSlimes => true,
            Cockatrice => false,
            Cows => true,
            Crabs => false,
            CrawlingHands => false,
            Crocodiles => true,
            CustodianStalker => false,
            Dagannoth => false,
            DustDevils => false,
            Dogs => true,
            Dwarves => true,
            Elves => false,
            FeverSpiders => false,
            FireGiants => WORLD_STATE != WorldState::Limp2024,
            FossilIslandWyverns => false,
            Gargoyles => false,
            Ghosts => true,
            Ghouls => false,
            Goblins => true,
            GreaterDemons => WORLD_STATE != WorldState::Limp2024,
            HarpieBugSwarms => false,
            Hellhounds => false,
            HillGiants => true,
            Hobgoblins => true,
            Icefiends => true,
            IceGiants => true,
            IceWarriors => true,
            InfernalMages => false,
            Jellies => false,
            JungleHorrors => false,
            Kalphite => true,
            Kurask => false,
            LesserDemons => false,
            LesserNagua => false,
            Lizardmen => false,
            Lizards => true,
            Minotaurs => true,
            Mogres => false,
            Molanisks => false,
            Monkeys => false,
            MossGiants => true,
            MutatedZygomites => WORLD_STATE != WorldState::Limp2024,
            Nechryael => false,
            Ogres => false,
            OtherwordlyBeings => WORLD_STATE != WorldState::Limp2024,
            Pyrefiends => WORLD_STATE != WorldState::Limp2024,
            Rats => true,
            Scorpions => true,
            SeaSnakes => false,
            Shades => true,
            ShadowWarriors => false,
            SkeletalWyverns => WORLD_STATE != WorldState::Limp2024,
            Skeletons => true,
            Sourhogs => true,
            Spiders => true,
            SpiritualCreatures => WORLD_STATE != WorldState::Limp2024,
            TerrorDogs => false,
            Trolls => false,
            Turoth => false,
            TzHaar => false,
            Vampyres => false,
            WarpedCreatures => false,
            Werewolves => false,
            Wolves => true,
            Wyrms => false,
            Zombies => true,
        }
    }

    pub fn slayer_exp(&self) -> u32 {
        use Monster::*;
        match self {
            AberrantSpectres => 90,
            AbyssalDemons => 150,
            Ankous => 60,
            Aviansie => 70,
            Banshees => 22,
            Basilisks => 75,
            Bats => 8,
            Bears => 27,
            Birds => 3,
            BlackDemons => 157,
            Bloodveld => 134,
            BlueDragons => 50, // Baby blue dragons
            BrineRats => 50,
            CaveBugs => 5,
            CaveCrawlers => 22,
            CaveHorrors => todo!(),
            CaveKraken => todo!(),
            CaveSlimes => 25,
            Cockatrice => todo!(),
            Cows => 8,
            Crabs => todo!(),
            CrawlingHands => todo!(),
            Crocodiles => 62,
            CustodianStalker => todo!(),
            Dagannoth => todo!(),
            DustDevils => todo!(),
            Dogs => 27,    // Jackals
            Dwarves => 15, // Average of the various dwarf levels
            Elves => todo!(),
            FeverSpiders => todo!(),
            FireGiants => 735, // Branda the Fire Queen
            FossilIslandWyverns => todo!(),
            Gargoyles => todo!(),
            Ghosts => 25, // lv 19 variant
            Ghouls => todo!(),
            Goblins => 7,         // Average of lv 2 and lv 5 variant
            GreaterDemons => 102, // Average of lv 91, 100 and 101 variants
            HarpieBugSwarms => todo!(),
            Hellhounds => todo!(),
            HillGiants => 35,
            Hobgoblins => 29,
            Icefiends => 17, // Average of lv 13 and lv 18 variants
            IceGiants => 70,
            IceWarriors => 59,
            InfernalMages => todo!(),
            Jellies => todo!(),
            JungleHorrors => todo!(),
            Kalphite => 40, // Kalphite workers
            Kurask => todo!(),
            LesserDemons => todo!(),
            LesserNagua => todo!(),
            Lizardmen => todo!(),
            Lizards => 40,
            Minotaurs => 15, // Average of lv 12 and lv 27 variants
            Mogres => todo!(),
            Molanisks => todo!(),
            Monkeys => todo!(),
            MossGiants => 60,       // Lv 42 variants
            MutatedZygomites => 70, // Average of lv 74 and lv 86 variants
            Nechryael => todo!(),
            Ogres => todo!(),
            OtherwordlyBeings => 66,
            Pyrefiends => 45,
            Rats => 2,
            Scorpions => 17,
            SeaSnakes => todo!(),
            Shades => 5,
            ShadowWarriors => todo!(),
            SkeletalWyverns => todo!(),
            Skeletons => 20, // Average of low-level variants
            Sourhogs => 40,
            Spiders => 2, // Level 1 spiders
            SpiritualCreatures => todo!(),
            TerrorDogs => todo!(),
            Trolls => 90, // Mountain trolls
            Turoth => todo!(),
            TzHaar => todo!(),
            Vampyres => todo!(),
            WarpedCreatures => todo!(),
            Werewolves => todo!(),
            Wolves => 12, // Average of lv 11 and lv 14 variants
            Wyrms => todo!(),
            Zombies => 24, // Level 18 variants
        }
    }

    pub fn slayer_req(&self) -> u8 {
        match self {
            Monster::AberrantSpectres => 60,
            Monster::AbyssalDemons => 85,
            Monster::Ankous => 0,
            Monster::Aviansie => 0,
            Monster::Banshees => 15,
            Monster::Basilisks => 40,
            Monster::Bats => 0,
            Monster::Bears => 0,
            Monster::Birds => 0,
            Monster::BlackDemons => 0,
            Monster::Bloodveld => 50,
            Monster::BlueDragons => 0,
            Monster::BrineRats => 47,
            Monster::CaveBugs => 7,
            Monster::CaveCrawlers => 10,
            Monster::CaveHorrors => 58,
            Monster::CaveKraken => 87,
            Monster::CaveSlimes => 17,
            Monster::Cockatrice => 25,
            Monster::Cows => 0,
            Monster::Crabs => 0,
            Monster::CrawlingHands => 5,
            Monster::Crocodiles => 0,
            Monster::CustodianStalker => 54,
            Monster::Dagannoth => 0,
            Monster::DustDevils => 65,
            Monster::Dogs => 0,
            Monster::Dwarves => 0,
            Monster::Elves => 0,
            Monster::FeverSpiders => 42,
            Monster::FireGiants => 0,
            Monster::FossilIslandWyverns => 66,
            Monster::Gargoyles => 75,
            Monster::Ghosts => 0,
            Monster::Ghouls => 0,
            Monster::Goblins => 0,
            Monster::GreaterDemons => 0,
            Monster::HarpieBugSwarms => 33,
            Monster::Hellhounds => 0,
            Monster::HillGiants => 0,
            Monster::Hobgoblins => 0,
            Monster::Icefiends => 0,
            Monster::IceGiants => 0,
            Monster::IceWarriors => 0,
            Monster::InfernalMages => 45,
            Monster::Jellies => 52,
            Monster::JungleHorrors => 0,
            Monster::Kalphite => 0,
            Monster::Kurask => 70,
            Monster::LesserDemons => 0,
            Monster::LesserNagua => 48,
            Monster::Lizardmen => 0,
            Monster::Lizards => 22,
            Monster::Minotaurs => 0,
            Monster::Mogres => 32,
            Monster::Molanisks => 39,
            Monster::Monkeys => 0,
            Monster::MossGiants => 0,
            Monster::MutatedZygomites => 57,
            Monster::Nechryael => 80,
            Monster::Ogres => 0,
            Monster::OtherwordlyBeings => 0,
            Monster::Pyrefiends => 30,
            Monster::Rats => 0,
            Monster::Scorpions => 0,
            Monster::SeaSnakes => 40,
            Monster::Shades => 0,
            Monster::ShadowWarriors => 0,
            Monster::SkeletalWyverns => 72,
            Monster::Skeletons => 0,
            Monster::Sourhogs => 1,
            Monster::Spiders => 0,
            Monster::SpiritualCreatures => 63,
            Monster::TerrorDogs => 40,
            Monster::Trolls => 0,
            Monster::Turoth => 55,
            Monster::TzHaar => 0,
            Monster::Vampyres => 0,
            Monster::WarpedCreatures => 0,
            Monster::Werewolves => 0,
            Monster::Wolves => 0,
            Monster::Wyrms => 62,
            Monster::Zombies => 0,
        }
    }
}

pub const TURAEL_ASSIGNMENTS: &[Assignment] = &[
    Assignment {
        monster: Monster::Banshees,
        amount: 15..=30,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 8,
    },
    Assignment {
        monster: Monster::Bats,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Bears,
        amount: 10..=20,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Birds,
        amount: 15..=30,
        quest_requirement: None,
        weight: 6,
    },
    Assignment {
        monster: Monster::CaveBugs,
        amount: 10..=30,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::CaveCrawlers,
        amount: 15..=30,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::CaveSlimes,
        amount: 10..=20,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::Cows,
        amount: 15..=30,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::CrawlingHands,
        amount: 15..=30,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 8,
    },
    Assignment {
        monster: Monster::Dogs,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Dwarves,
        amount: 10..=25,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Ghosts,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Goblins,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Icefiends,
        amount: 15..=20,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::Kalphite,
        amount: 15..=30,
        quest_requirement: None,
        weight: 6,
    },
    Assignment {
        monster: Monster::Lizards,
        amount: 15..=30,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::Minotaurs,
        amount: 10..=20,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Monkeys,
        amount: 15..=30,
        quest_requirement: None,
        weight: 6,
    },
    Assignment {
        monster: Monster::Rats,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Scorpions,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Skeletons,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Spiders,
        amount: 15..=30,
        quest_requirement: None,
        weight: 6,
    },
    Assignment {
        monster: Monster::Wolves,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Zombies,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
];

pub const SPRIA_ASSIGNMENTS: &[Assignment] = &[
    Assignment {
        monster: Monster::Banshees,
        amount: 15..=30,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 8,
    },
    Assignment {
        monster: Monster::Bats,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Bears,
        amount: 10..=20,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Birds,
        amount: 15..=30,
        quest_requirement: None,
        weight: 6,
    },
    Assignment {
        monster: Monster::CaveBugs,
        amount: 10..=30,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::CaveCrawlers,
        amount: 15..=30,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::CaveSlimes,
        amount: 10..=20,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::Cows,
        amount: 15..=30,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::CrawlingHands,
        amount: 15..=30,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 8,
    },
    Assignment {
        monster: Monster::Dogs,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Dwarves,
        amount: 10..=25,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Ghosts,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Goblins,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Icefiends,
        amount: 15..=20,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::Kalphite,
        amount: 15..=30,
        quest_requirement: None,
        weight: 6,
    },
    Assignment {
        monster: Monster::Lizards,
        amount: 15..=30,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::Minotaurs,
        amount: 10..=20,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Monkeys,
        amount: 15..=30,
        quest_requirement: None,
        weight: 6,
    },
    Assignment {
        monster: Monster::Rats,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Scorpions,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Skeletons,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Sourhogs,
        amount: 15..=25,
        quest_requirement: Some(Quest::PorcineOfInterest),
        weight: 6,
    },
    Assignment {
        monster: Monster::Spiders,
        amount: 15..=30,
        quest_requirement: None,
        weight: 6,
    },
    Assignment {
        monster: Monster::Wolves,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Zombies,
        amount: 15..=30,
        quest_requirement: None,
        weight: 7,
    },
];

pub const VANNAKA_ASSIGNMENTS: &[Assignment] = &[
    Assignment {
        monster: Monster::AberrantSpectres,
        amount: 40..=90,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 8,
    },
    Assignment {
        monster: Monster::AbyssalDemons,
        amount: 40..=90,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 5,
    },
    Assignment {
        monster: Monster::Ankous,
        amount: 25..=35,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Basilisks,
        amount: 40..=90,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::Bloodveld,
        amount: 40..=90,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 8,
    },
    Assignment {
        monster: Monster::BlueDragons,
        amount: 40..=90,
        quest_requirement: Some(Quest::DragonSlayer),
        weight: 7,
    },
    Assignment {
        monster: Monster::BrineRats,
        amount: 40..=90,
        quest_requirement: Some(Quest::OlafsQuest),
        weight: 7,
    },
    Assignment {
        monster: Monster::Cockatrice,
        amount: 40..=90,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::Crabs,
        amount: 40..=90,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::Crocodiles,
        amount: 40..=90,
        quest_requirement: None,
        weight: 6,
    },
    Assignment {
        monster: Monster::Dagannoth,
        amount: 40..=90,
        quest_requirement: Some(Quest::HorrorFromTheDeep),
        weight: 7,
    },
    Assignment {
        monster: Monster::DustDevils,
        amount: 40..=90,
        quest_requirement: Some(Quest::DesertTreasure),
        weight: 8,
    },
    Assignment {
        monster: Monster::Elves,
        amount: 30..=70,
        quest_requirement: Some(Quest::Regicide),
        weight: 7,
    },
    Assignment {
        monster: Monster::FeverSpiders,
        amount: 30..=90,
        quest_requirement: Some(Quest::RumDeal),
        weight: 7,
    },
    Assignment {
        monster: Monster::FireGiants,
        amount: 40..=90,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Gargoyles,
        amount: 40..=90,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 5,
    },
    Assignment {
        monster: Monster::Ghouls,
        amount: 10..=40,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 7,
    },
    Assignment {
        monster: Monster::HarpieBugSwarms,
        amount: 40..=90,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::Hellhounds,
        amount: 30..=60,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::HillGiants,
        amount: 40..=90,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Hobgoblins,
        amount: 40..=90,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::IceGiants,
        amount: 30..=80,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::IceWarriors,
        amount: 40..=90,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::InfernalMages,
        amount: 40..=90,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 8,
    },
    Assignment {
        monster: Monster::Jellies,
        amount: 40..=90,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::JungleHorrors,
        amount: 40..=90,
        quest_requirement: Some(Quest::CabinFever),
        weight: 8,
    },
    Assignment {
        monster: Monster::Kalphite,
        amount: 40..=90,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Kurask,
        amount: 40..=90,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::LesserDemons,
        amount: 40..=90,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Mogres,
        amount: 40..=90,
        quest_requirement: Some(Quest::SkippyAndTheMogres),
        weight: 7,
    },
    Assignment {
        monster: Monster::Molanisks,
        amount: 40..=50,
        quest_requirement: Some(Quest::DeathToTheDorgeshuun),
        weight: 7,
    },
    Assignment {
        monster: Monster::MossGiants,
        amount: 40..=90,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Nechryael,
        amount: 40..=90,
        quest_requirement: None,
        weight: 5,
    },
    Assignment {
        monster: Monster::Ogres,
        amount: 40..=90,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::OtherwordlyBeings,
        amount: 40..=90,
        quest_requirement: Some(Quest::LostCity),
        weight: 8,
    },
    Assignment {
        monster: Monster::Pyrefiends,
        amount: 40..=90,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::SeaSnakes,
        amount: 40..=90,
        quest_requirement: Some(Quest::RoyalTrouble),
        weight: 6,
    },
    Assignment {
        monster: Monster::Shades,
        amount: 40..=90,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::ShadowWarriors,
        amount: 40..=90,
        quest_requirement: Some(Quest::LegendsQuest),
        weight: 8,
    },
    Assignment {
        monster: Monster::SpiritualCreatures,
        amount: 40..=90,
        quest_requirement: Some(Quest::DeathPlateau),
        weight: 8,
    },
    Assignment {
        monster: Monster::TerrorDogs,
        amount: 40..=90,
        quest_requirement: Some(Quest::HauntedMine),
        weight: 6,
    },
    Assignment {
        monster: Monster::Trolls,
        amount: 40..=90,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::Turoth,
        amount: 30..=90,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::Vampyres,
        amount: 10..=20,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 7,
    },
    Assignment {
        monster: Monster::Werewolves,
        amount: 30..=60,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 7,
    },
];

pub const CHAELDAR_ASSIGNMENTS: &[Assignment] = &[
    Assignment {
        monster: Monster::AberrantSpectres,
        amount: 70..=130,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 8,
    },
    Assignment {
        monster: Monster::AbyssalDemons,
        amount: 70..=130,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 12,
    },
    Assignment {
        monster: Monster::Aviansie,
        amount: 70..=130,
        quest_requirement: Some(Quest::WatchTheBirdie),
        weight: 9,
    },
    Assignment {
        monster: Monster::Basilisks,
        amount: 70..=130,
        quest_requirement: None,
        weight: 7,
    },
    Assignment {
        monster: Monster::BlackDemons,
        amount: 70..=130,
        quest_requirement: None,
        weight: 10,
    },
    Assignment {
        monster: Monster::Bloodveld,
        amount: 70..=130,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 8,
    },
    Assignment {
        monster: Monster::BlueDragons,
        amount: 70..=130,
        quest_requirement: Some(Quest::DragonSlayer),
        weight: 8,
    },
    Assignment {
        monster: Monster::BrineRats,
        amount: 70..=130,
        quest_requirement: Some(Quest::OlafsQuest),
        weight: 7,
    },
    Assignment {
        monster: Monster::CaveHorrors,
        amount: 70..=130,
        quest_requirement: Some(Quest::CabinFever),
        weight: 10,
    },
    Assignment {
        monster: Monster::CaveKraken,
        amount: 30..=50,
        quest_requirement: None,
        weight: 12,
    },
    Assignment {
        monster: Monster::Crabs,
        amount: 70..=130,
        quest_requirement: None,
        weight: 8,
    },
    Assignment {
        monster: Monster::CustodianStalker,
        amount: 70..=130,
        quest_requirement: Some(Quest::ShadowsOfCustodia),
        weight: 11,
    },
    Assignment {
        monster: Monster::Dagannoth,
        amount: 70..=130,
        quest_requirement: Some(Quest::HorrorFromTheDeep),
        weight: 11,
    },
    Assignment {
        monster: Monster::DustDevils,
        amount: 70..=130,
        quest_requirement: Some(Quest::DesertTreasure),
        weight: 9,
    },
    Assignment {
        monster: Monster::Elves,
        amount: 70..=130,
        quest_requirement: Some(Quest::Regicide),
        weight: 8,
    },
    Assignment {
        monster: Monster::FeverSpiders,
        amount: 70..=130,
        quest_requirement: Some(Quest::RumDeal),
        weight: 7,
    },
    Assignment {
        monster: Monster::FireGiants,
        amount: 70..=130,
        quest_requirement: None,
        weight: 12,
    },
    Assignment {
        monster: Monster::FossilIslandWyverns,
        amount: 10..=20,
        quest_requirement: Some(Quest::ElementalWorkshop),
        weight: 7,
    },
    Assignment {
        monster: Monster::Gargoyles,
        amount: 70..=130,
        quest_requirement: Some(Quest::PriestInPeril),
        weight: 11,
    },
    Assignment {
        monster: Monster::GreaterDemons,
        amount: 70..=130,
        quest_requirement: None,
        weight: 9,
    },
    Assignment {
        monster: Monster::Hellhounds,
        amount: 70..=130,
        quest_requirement: None,
        weight: 9,
    },
    Assignment {
        monster: Monster::Jellies,
        amount: 70..=130,
        quest_requirement: None,
        weight: 10,
    },
    Assignment {
        monster: Monster::JungleHorrors,
        amount: 70..=130,
        quest_requirement: Some(Quest::CabinFever),
        weight: 10,
    },
    Assignment {
        monster: Monster::Kalphite,
        amount: 70..=130,
        quest_requirement: None,
        weight: 11,
    },
    Assignment {
        monster: Monster::Kurask,
        amount: 70..=130,
        quest_requirement: None,
        weight: 12,
    },
    Assignment {
        monster: Monster::LesserDemons,
        amount: 70..=130,
        quest_requirement: None,
        weight: 9,
    },
    Assignment {
        monster: Monster::LesserNagua,
        amount: 50..=100,
        quest_requirement: Some(Quest::PerilousMoons),
        weight: 4,
    },
    Assignment {
        monster: Monster::Lizardmen,
        amount: 50..=90,
        quest_requirement: Some(Quest::ReptileGotRipped),
        weight: 8,
    },
    Assignment {
        monster: Monster::MutatedZygomites,
        amount: 8..=15,
        quest_requirement: Some(Quest::LostCity),
        weight: 7,
    },
    Assignment {
        monster: Monster::Nechryael,
        amount: 70..=130,
        quest_requirement: None,
        weight: 12,
    },
    Assignment {
        monster: Monster::ShadowWarriors,
        amount: 70..=130,
        quest_requirement: Some(Quest::LegendsQuest),
        weight: 8,
    },
    Assignment {
        monster: Monster::SkeletalWyverns,
        amount: 10..=20,
        quest_requirement: Some(Quest::ElementalWorkshop),
        weight: 7,
    },
    Assignment {
        monster: Monster::SpiritualCreatures,
        amount: 70..=130,
        quest_requirement: Some(Quest::DeathPlateau),
        weight: 12,
    },
    Assignment {
        monster: Monster::Trolls,
        amount: 70..=130,
        quest_requirement: None,
        weight: 11,
    },
    Assignment {
        monster: Monster::Turoth,
        amount: 70..=130,
        quest_requirement: None,
        weight: 10,
    },
    Assignment {
        monster: Monster::TzHaar,
        amount: 90..=150,
        quest_requirement: Some(Quest::HotStuff),
        weight: 8,
    },
    Assignment {
        monster: Monster::Vampyres,
        amount: 80..=100,
        quest_requirement: Some(Quest::ActualVampyreSlayer),
        weight: 6,
    },
    Assignment {
        monster: Monster::WarpedCreatures,
        amount: 70..=130,
        quest_requirement: Some(Quest::WarpedReality),
        weight: 6,
    },
    Assignment {
        monster: Monster::Wyrms,
        amount: 60..=100,
        quest_requirement: None,
        weight: 6,
    },
];
